force-app/main/default/objects/Alocacao__c/Alocacao__c.object-meta.xml
<CustomObject>
    <label>Alocação</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alocações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Alocacao__c/fields/CustoRealizado__c.field-meta.xml
<CustomField>
    <fullName>CustoRealizado__c</fullName>
    <label>Custo Realizado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Alocacao__c/fields/Servico__c.field-meta.xml
<CustomField>
    <fullName>Servico__c</fullName>
    <label>Serviço</label>
    <referenceTo>Servico__c</referenceTo>
    <relationshipLabel>Alocações</relationshipLabel>
    <relationshipName>Alocacoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LancamentoHora__c/LancamentoHora__c.object-meta.xml
<CustomObject>
    <label>Lançamento de hora</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lançamentos de horas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LancamentoHora__c/fields/DiaPeriodo__c.field-meta.xml
<CustomField>
    <fullName>DiaPeriodo__c</fullName>
    <label>Dia do período</label>
    <referenceTo>DiaPeriodo__c</referenceTo>
    <relationshipLabel>Lançamentos de horas</relationshipLabel>
    <relationshipName>LancamentosHoras</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LancamentoHora__c/fields/Horas__c.field-meta.xml
<CustomField>
    <fullName>Horas__c</fullName>
    <label>Horas</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LancamentoHora__c/fields/HorasExtras__c.field-meta.xml
<CustomField>
    <fullName>HorasExtras__c</fullName>
    <label>Horas extras</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LancamentoHora__c/fields/OrcamentoCompetencia__c.field-meta.xml
<CustomField>
    <fullName>OrcamentoCompetencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vínculo com a competência onde o custo foi apurado.</description>
    <label>Orçamento Competência</label>
    <referenceTo>OrcamentoCompetencia__c</referenceTo>
    <relationshipLabel>Lançamentos de Horas (Custo)</relationshipLabel>
    <relationshipName>LancamentosHorasCusto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LancamentoHora__c/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <label>Responsável</label>
    <referenceTo>Responsavel__c</referenceTo>
    <relationshipLabel>Lançamentos de horas</relationshipLabel>
    <relationshipName>LancamentosHoras</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LancamentoHora__c/fields/Servico__c.field-meta.xml
<CustomField>
    <fullName>Servico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serviço</label>
    <referenceTo>Servico__c</referenceTo>
    <relationshipLabel>Lançamentos de horas</relationshipLabel>
    <relationshipName>LancamentosHoras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LancamentoHora__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Rascunho&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lançado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em aprovação do serviço</fullName>
            </value>
            <value>
                <fullName>Em aprovação do RH</fullName>
            </value>
            <value>
                <fullName>Reprovado serviço</fullName>
            </value>
            <value>
                <fullName>Reprovado RH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LancamentoHora__c/fields/ValorTotalLancamento__c.field-meta.xml
<CustomField>
    <fullName>ValorTotalLancamento__c</fullName>
    <formula>( DiaPeriodo__r.Periodo__r.ValorHora__c +  DiaPeriodo__r.Periodo__r.ValorHoraBeneficios__c ) * ( Horas__c +  2*HorasExtras__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor total lançamento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrcamentoCompetencia__c/OrcamentoCompetencia__c.object-meta.xml
<CustomObject>
    <description>Orçamento mensal por competência e profissional alocado.</description>
    <label>Orçamento Competência</label>
    <nameField>
        <displayFormat>OC-{000000}</displayFormat>
        <label>ID Orçamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orçamentos Competência</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrcamentoCompetencia__c/fields/Alocacao__c.field-meta.xml
<CustomField>
    <fullName>Alocacao__c</fullName>
    <description>Alocação pai deste orçamento mensal.</description>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Alocação</label>
    <referenceTo>Alocacao__c</referenceTo>
    <relationshipLabel>Orçamentos Competência</relationshipLabel>
    <relationshipName>OrcamentosCompetencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrcamentoCompetencia__c/fields/Competencia__c.field-meta.xml
<CustomField>
    <fullName>Competencia__c</fullName>
    <description>Data de referência (geralmente dia 1 do mês).</description>
    <label>Competência</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrcamentoCompetencia__c/fields/CustoPrevisto__c.field-meta.xml
<CustomField>
    <fullName>CustoPrevisto__c</fullName>
    <label>Custo Previsto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrcamentoCompetencia__c/fields/HorasRealizadas__c.field-meta.xml
<CustomField>
    <fullName>HorasRealizadas__c</fullName>
    <label>Horas Realizadas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrcamentoCompetencia__c/fields/ReceitaPrevista__c.field-meta.xml
<CustomField>
    <fullName>ReceitaPrevista__c</fullName>
    <label>Receita Prevista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrcamentoCompetencia__c/fields/ReceitaRealizada__c.field-meta.xml
<CustomField>
    <fullName>ReceitaRealizada__c</fullName>
    <description>Soma das distribuições de receita realizadas via parcelas faturadas.</description>
    <label>Receita Realizada</label>
    <summarizedField>DistribuicaoReceita__c.ValorDistribuido__c</summarizedField>
    <summaryForeignKey>DistribuicaoReceita__c.OrcamentoCompetencia__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OrcamentoCompetencia__c/fields/Servico__c.field-meta.xml
<CustomField>
    <fullName>Servico__c</fullName>
    <label>Serviço</label>
    <type>Lookup</type>
    <referenceTo>Servico__c</referenceTo>
    <relationshipLabel>Orçamentos de Competência (Geral)</relationshipLabel>
    <relationshipName>OrcamentosCompetenciaGeral</relationshipName>
</CustomField>

force-app/main/default/objects/Servico__c/Servico__c.object-meta.xml
<CustomObject>
    <label>Serviço</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serviços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servico__c/fields/CustoPrevisto__c.field-meta.xml
<CustomField>
    <fullName>CustoPrevisto__c</fullName>
    <label>Custo Previsto (Total)</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Servico__c/fields/CustoRealizado__c.field-meta.xml
<CustomField>
    <fullName>CustoRealizado__c</fullName>
    <label>Custo Realizado (Total)</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Servico__c/fields/MargemRealizada__c.field-meta.xml
<CustomField>
    <fullName>MargemRealizada__c</fullName>
    <label>Margem Realizada (%)</label>
    <type>Percent</type>
    <precision>5</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ReceitaPrevista__c.field-meta.xml
<CustomField>
    <fullName>ReceitaPrevista__c</fullName>
    <label>Receita Prevista (Total)</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ReceitaRealizada__c.field-meta.xml
<CustomField>
    <fullName>ReceitaRealizada__c</fullName>
    <label>Receita Realizada (Total)</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Calcula se o serviço está ativo baseando-se na data de início e fim em relação a hoje.</description>
    <formula>IF(AND(DataInicio__c &lt;= TODAY(), OR(ISBLANK(DataFim__c), DataFim__c &gt;= TODAY())), &quot;Ativo&quot;, &quot;Inativo&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApuracaoCustosBatch.cls
public with sharing class ApuracaoCustosBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    // Conjunto de IDs de Serviços e Alocações afetados para recalcular totais no finish
    private Set<Id> serviceIds = new Set<Id>();
    private Set<Id> allocationIds = new Set<Id>();

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id, Servico__c, Responsavel__c, Responsavel__r.Alocacao__c, 
                   DiaPeriodo__c, DiaPeriodo__r.Data__c, 
                   ValorTotalLancamento__c, Horas__c, HorasExtras__c 
            FROM LancamentoHora__c 
            WHERE Status__c = 'Faturado' 
            AND OrcamentoCompetencia__c = null
            AND Responsavel__r.Alocacao__c != null
        ]);
    }

    public void execute(Database.BatchableContext BC, List<LancamentoHora__c> scope) {
        Map<String, List<LancamentoHora__c>> agrupamento = new Map<String, List<LancamentoHora__c>>();
        
        for (LancamentoHora__c lh : scope) {
            Date dt = (lh.DiaPeriodo__r != null) ? lh.DiaPeriodo__r.Data__c : null;
            if (dt == null) continue;
            
            Date dataCompetencia = dt.toStartOfMonth();
            Id allocId = lh.Responsavel__r.Alocacao__c;
            String key = allocId + '_' + String.valueOf(dataCompetencia);
            
            if (!agrupamento.containsKey(key)) {
                agrupamento.put(key, new List<LancamentoHora__c>());
            }
            agrupamento.get(key).add(lh);
            
            serviceIds.add(lh.Servico__c);
            allocationIds.add(allocId);
        }

        if (agrupamento.isEmpty()) return;

        Map<String, OrcamentoCompetencia__c> orcMap = new Map<String, OrcamentoCompetencia__c>();
        for (OrcamentoCompetencia__c orc : [
            SELECT Id, Alocacao__c, Competencia__c 
            FROM OrcamentoCompetencia__c 
            WHERE Alocacao__c IN :allocationIds
        ]) {
            String key = orc.Alocacao__c + '_' + String.valueOf(orc.Competencia__c);
            orcMap.put(key, orc);
        }

        List<OrcamentoCompetencia__c> newOrcs = new List<OrcamentoCompetencia__c>();
        for (String key : agrupamento.keySet()) {
            if (!orcMap.containsKey(key)) {
                String[] parts = key.split('_');
                Id aId = (Id)parts[0];
                Date cDate = Date.valueOf(parts[1]);
                Id sId = agrupamento.get(key)[0].Servico__c;

                newOrcs.add(new OrcamentoCompetencia__c(
                    Alocacao__c = aId,
                    Servico__c = sId,
                    Competencia__c = cDate,
                    ReceitaPrevista__c = 0,
                    CustoPrevisto__c = 0,
                    CustoRealizado__c = 0,
                    HorasRealizadas__c = 0
                ));
            }
        }
        if (!newOrcs.isEmpty()) {
            insert newOrcs;
            for (OrcamentoCompetencia__c orc : newOrcs) {
                orcMap.put(orc.Alocacao__c + '_' + String.valueOf(orc.Competencia__c), orc);
            }
        }

        List<LancamentoHora__c> lhToUpdate = new List<LancamentoHora__c>();
        Map<Id, Decimal> deltaCusto = new Map<Id, Decimal>();
        Map<Id, Decimal> deltaHoras = new Map<Id, Decimal>();

        for (String key : agrupamento.keySet()) {
            OrcamentoCompetencia__c orc = orcMap.get(key);
            if (orc == null) continue;

            Decimal custoTotal = 0;
            Decimal horasTotal = 0;

            for (LancamentoHora__c lh : agrupamento.get(key)) {
                lh.OrcamentoCompetencia__c = orc.Id;
                lhToUpdate.add(lh);
                
                custoTotal += (lh.ValorTotalLancamento__c != null ? lh.ValorTotalLancamento__c : 0);
                horasTotal += (lh.Horas__c != null ? lh.Horas__c : 0) + (2 * (lh.HorasExtras__c != null ? lh.HorasExtras__c : 0));
            }

            deltaCusto.put(orc.Id, custoTotal);
            deltaHoras.put(orc.Id, horasTotal);
        }

        if (!lhToUpdate.isEmpty()) update lhToUpdate;
        
        List<OrcamentoCompetencia__c> finalOrcUpdates = new List<OrcamentoCompetencia__c>();
        for (OrcamentoCompetencia__c dbOrc : [SELECT Id, CustoRealizado__c, HorasRealizadas__c FROM OrcamentoCompetencia__c WHERE Id IN :deltaCusto.keySet()]) {
            dbOrc.CustoRealizado__c = (dbOrc.CustoRealizado__c != null ? dbOrc.CustoRealizado__c : 0) + deltaCusto.get(dbOrc.Id);
            dbOrc.HorasRealizadas__c = (dbOrc.HorasRealizadas__c != null ? dbOrc.HorasRealizadas__c : 0) + deltaHoras.get(dbOrc.Id);
            finalOrcUpdates.add(dbOrc);
        }
        if (!finalOrcUpdates.isEmpty()) update finalOrcUpdates;
    }

    public void finish(Database.BatchableContext BC) {
        if (!allocationIds.isEmpty()) {
            recalculateTotals();
        }
        System.debug('Apuração de Custos finalizada.');
    }

    private void recalculateTotals() {
        // 1. Totalizar Orçamentos -> Alocação
        List<Alocacao__c> allocsToUpdate = new List<Alocacao__c>();
        for (AggregateResult ar : [
            SELECT Alocacao__c id, SUM(CustoRealizado__c) total 
            FROM OrcamentoCompetencia__c 
            WHERE Alocacao__c IN :allocationIds 
            GROUP BY Alocacao__c
        ]) {
            allocsToUpdate.add(new Alocacao__c(
                Id = (Id)ar.get('id'),
                CustoRealizado__c = (Decimal)ar.get('total')
            ));
        }
        if (!allocsToUpdate.isEmpty()) update allocsToUpdate;

        // 2. Totalizar Alocações -> Serviço
        List<Servico__c> svcsToUpdate = new List<Servico__c>();
        
        // Buscar informações de receita de todos os serviços de uma vez
        Map<Id, Servico__c> sMap = new Map<Id, Servico__c>([
            SELECT Id, ReceitaRealizada__c FROM Servico__c WHERE Id IN :serviceIds
        ]);

        for (AggregateResult ar : [
            SELECT Servico__c id, SUM(CustoRealizado__c) total 
            FROM Alocacao__c 
            WHERE Servico__c IN :serviceIds 
            GROUP BY Servico__c
        ]) {
            Id sid = (Id)ar.get('id');
            Decimal custReal = (Decimal)ar.get('total');
            
            Decimal recReal = sMap.containsKey(sid) && sMap.get(sid).ReceitaRealizada__c != null ? 
                              sMap.get(sid).ReceitaRealizada__c : 0;
            
            Decimal margReal = 0;
            if (recReal > 0) {
                margReal = ((recReal - custReal) / recReal) * 100;
            }

            svcsToUpdate.add(new Servico__c(
                Id = sid,
                CustoRealizado__c = custReal,
                MargemRealizada__c = margReal
            ));
        }
        if (!svcsToUpdate.isEmpty()) update svcsToUpdate;
    }
}